# Generated by Django 6.0.3 on 2026-08-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_google_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signupotp',
            options={},
        ),
        migrations.RemoveField(
            model_name='signupotp',
            name='department',
        ),
        migrations.RemoveField(
            model_name='signupotp',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='signupotp',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='signupotp',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='signupotp',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='signupotp',
            name='student_id',
        ),
    ]
