# Generated by Django 6.0.3 on 2026-08-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_signupotp_options_remove_signupotp_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupotp',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='signupotp',
            name='first_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupotp',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='signupotp',
            name='password_hash',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupotp',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='signupotp',
            name='student_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
